apiVersion: v1
kind: ResourceQuota
metadata:
  name: tippay-quota
  namespace: tippay
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "20" 