apiVersion: v1
kind: Secret
metadata:
  name: security-secrets
  namespace: tippay
type: Opaque
data:
  jwt-secret: ${JWT_SECRET_BASE64}
  encryption-key: ${ENCRYPTION_KEY_BASE64}
  keystore-password: ${KEYSTORE_PASSWORD_BASE64}
  oauth-client-secret: ${OAUTH_CLIENT_SECRET_BASE64} 