apiVersion: apps/v1
kind: Deployment
metadata:
  name: tippay-mtf
  namespace: tippay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tippay-mtf
  template:
    metadata:
      labels:
        app: tippay-mtf
    spec:
      containers:
      - name: mtf
        image: tippay/mtf:latest
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: tippay-config
              key: db_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tippay-secrets
              key: jwt_secret
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tippay-data-processor
  namespace: tippay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tippay-data-processor
  template:
    metadata:
      labels:
        app: tippay-data-processor
    spec:
      containers:
      - name: data-processor
        image: tippay/data-processor:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch-service"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi" 