name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push MTF service
      uses: docker/build-push-action@v4
      with:
        context: ./mtf
        push: true
        tags: tippay/mtf:${{ github.sha }},tippay/mtf:latest
        cache-from: type=registry,ref=tippay/mtf:latest
        cache-to: type=inline

    - name: Build and push Data Processor
      uses: docker/build-push-action@v4
      with:
        context: ./data-layer
        push: true
        tags: tippay/data-processor:${{ github.sha }},tippay/data-processor:latest

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_STAGING }}

    - name: Update deployment images
      run: |
        kubectl set image deployment/tippay-mtf mtf=tippay/mtf:${{ github.sha }} -n tippay
        kubectl set image deployment/tippay-data-processor data-processor=tippay/data-processor:${{ github.sha }} -n tippay

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/tippay-mtf -n tippay
        kubectl rollout status deployment/tippay-data-processor -n tippay

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://api.tippay.com
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_PROD }}

    - name: Update production deployments
      run: |
        kubectl set image deployment/tippay-mtf mtf=tippay/mtf:${{ github.sha }} -n tippay
        kubectl set image deployment/tippay-data-processor data-processor=tippay/data-processor:${{ github.sha }} -n tippay

    - name: Wait for production rollout
      run: |
        kubectl rollout status deployment/tippay-mtf -n tippay
        kubectl rollout status deployment/tippay-data-processor -n tippay 